# Generated by Django 2.2.6 on 2019-12-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beak', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
